language: python
python:
    - "2.6"
    - "2.7"
services:
    - mongodb
    - rabbitmq
install:
    - pip install --allow-all-external -r requirements.txt
    - pip install coveralls
script:
    coverage run --source=database,scheduler,fetcher,processor,result,libs --omit=libs/sample_handler.py,libs/pprint.py ./runtest.py
after_success:
    - coverage combine
    - coveralls
