sudo: required
language: python
cache: pip
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
services:
    - docker
    - mongodb
    - rabbitmq
    - redis-server
    - elasticsearch
addons:
    postgresql: "9.4"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y beanstalkd
    - echo "START=yes" | sudo tee -a /etc/default/beanstalkd > /dev/null
    - sudo service beanstalkd start
    - sudo docker pull scrapinghub/splash
    - sudo docker run -d -p 5023:5023 -p 8050:8050 -p 8051:8051 scrapinghub/splash
before_script:
    - psql -c "CREATE DATABASE pyspider_test_taskdb ENCODING 'UTF8' TEMPLATE=template0;" -U postgres
    - psql -c "CREATE DATABASE pyspider_test_projectdb ENCODING 'UTF8' TEMPLATE=template0;" -U postgres
    - psql -c "CREATE DATABASE pyspider_test_resultdb ENCODING 'UTF8' TEMPLATE=template0;" -U postgres
    - sleep 10
install:
    - pip install http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.0.4.zip#md5=3df394d89300db95163f17c843ef49df
    - pip install --no-use-wheel lxml
    - pip install --allow-all-external -e .[all,test]
    - pip install coveralls
script:
    - coverage run setup.py test
after_success:
    - coverage combine
    - coveralls
